import type { Student } from "@/shared/schemas/students"

// Datos mock de alumnos. Satisfacen studentSchema y se sustituyen por las
// respuestas reales del backend (GET /students) cuando exista el módulo.

export const mockStudents: Student[] = [
  {
    id: "st-001",
    slug: "mateo-rodriguez",
    firstName: "Mateo",
    lastName: "Rodríguez",
    belt: "BLANCO",
    status: "ACTIVE",
    email: "mateo.r@example.com",
    phone: "+58 412 5551020",
    accessUsername: "mateo.r@example.com",
    enabledContent: ["kata-heian-shodan", "kihon-basico"],
    enrolledAt: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "st-002",
    slug: "valentina-gomez",
    firstName: "Valentina",
    lastName: "Gómez",
    belt: "AMARILLO",
    status: "ACTIVE",
    guardianName: "Carla Gómez",
    phone: "+58 414 5559988",
    accessUsername: "valentina.gomez@example.com",
    enabledContent: ["kata-heian-shodan", "kata-heian-nidan", "kihon-basico"],
    enrolledAt: "2025-09-03T00:00:00.000Z",
  },
  {
    id: "st-003",
    slug: "sebastian-perez",
    firstName: "Sebastián",
    lastName: "Pérez",
    belt: "NARANJA",
    status: "ACTIVE",
    email: "seba.perez@example.com",
    accessUsername: "seba.perez@example.com",
    enabledContent: ["kata-heian-nidan", "kumite-gohon", "terminologia"],
    enrolledAt: "2025-06-20T00:00:00.000Z",
  },
  {
    id: "st-004",
    slug: "isabella-martinez",
    firstName: "Isabella",
    lastName: "Martínez",
    belt: "VERDE",
    status: "INACTIVE",
    guardianName: "Luis Martínez",
    phone: "+58 416 5552233",
    accessUsername: "isabella.martinez@example.com",
    enabledContent: ["kumite-gohon", "kumite-kihon-ippon"],
    enrolledAt: "2024-11-11T00:00:00.000Z",
  },
  {
    id: "st-005",
    slug: "diego-fernandez",
    firstName: "Diego",
    lastName: "Fernández",
    belt: "AZUL",
    status: "ACTIVE",
    email: "diego.f@example.com",
    accessUsername: "diego.f@example.com",
    enabledContent: ["kumite-kihon-ippon", "terminologia"],
    enrolledAt: "2024-03-08T00:00:00.000Z",
  },
  {
    id: "st-006",
    slug: "camila-torres",
    firstName: "Camila",
    lastName: "Torres",
    belt: "MARRON",
    status: "ACTIVE",
    email: "camila.torres@example.com",
    phone: "+58 412 5557766",
    accessUsername: "camila.torres@example.com",
    enabledContent: [
      "kata-heian-shodan",
      "kata-heian-nidan",
      "kumite-kihon-ippon",
    ],
    enrolledAt: "2023-07-19T00:00:00.000Z",
  },
  {
    id: "st-007",
    slug: "lucas-diaz",
    firstName: "Lucas",
    lastName: "Díaz",
    belt: "NEGRO",
    status: "ACTIVE",
    email: "lucas.diaz@example.com",
    accessUsername: "lucas.diaz@example.com",
    enabledContent: [
      "kata-heian-shodan",
      "kata-heian-nidan",
      "kihon-basico",
      "kumite-gohon",
      "kumite-kihon-ippon",
      "terminologia",
    ],
    enrolledAt: "2022-02-01T00:00:00.000Z",
  },
  {
    id: "st-008",
    slug: "sofia-ramirez",
    firstName: "Sofía",
    lastName: "Ramírez",
    belt: "AMARILLO",
    status: "INACTIVE",
    guardianName: "Ana Ramírez",
    accessUsername: "sofia.ramirez@example.com",
    enabledContent: ["kata-heian-shodan"],
    enrolledAt: "2025-10-30T00:00:00.000Z",
  },
]
