import type { SyllabusItem } from "@/shared/schemas/content"

// Mock propio del módulo de contenido (no es el mismo mock que
// modules/students/content-mock.ts, que sirve al selector de alumnos).

export const mockSyllabusItems: SyllabusItem[] = [
  {
    id: "syl-1",
    slug: "kata-heian-shodan",
    type: "KATA",
    title: "Heian Shodan",
    bodyMarkdown: "Primer kata de la serie Heian. Énfasis en zenkutsu-dachi.",
    videoUrl: "",
    minBeltRank: "BLANCO",
    style: "SHOTOKAN",
    createdAt: "2025-01-10T10:00:00.000Z",
  },
  {
    id: "syl-2",
    slug: "kihon-basico",
    type: "PROGRAM",
    title: "Kihon básico",
    bodyMarkdown: "Golpes y bloqueos fundamentales para cinta blanca.",
    videoUrl: "https://example.com/video/kihon-basico",
    minBeltRank: "BLANCO",
    style: "SHOTOKAN",
    createdAt: "2025-01-10T10:00:00.000Z",
  },
  {
    id: "syl-3",
    slug: "kata-heian-nidan",
    type: "KATA",
    title: "Heian Nidan",
    bodyMarkdown: "Segundo kata de la serie Heian.",
    videoUrl: "",
    minBeltRank: "AMARILLO",
    style: "SHOTOKAN",
    createdAt: "2025-02-05T10:00:00.000Z",
  },
  {
    id: "syl-4",
    slug: "bunkai-heian-shodan",
    type: "BUNKAI",
    title: "Bunkai: Heian Shodan",
    bodyMarkdown: "Aplicación marcial de las primeras técnicas de Heian Shodan.",
    videoUrl: "https://example.com/video/bunkai-heian-shodan",
    minBeltRank: "AMARILLO",
    style: "SHOTOKAN",
    createdAt: "2025-02-20T10:00:00.000Z",
  },
  {
    id: "syl-5",
    slug: "kumite-gohon",
    type: "PROGRAM",
    title: "Kumite: Gohon",
    bodyMarkdown: "Combate acordado de cinco pasos.",
    videoUrl: "",
    minBeltRank: "NARANJA",
    style: "SHOTOKAN",
    createdAt: "2025-03-01T10:00:00.000Z",
  },
  {
    id: "syl-6",
    slug: "kata-heian-sandan",
    type: "KATA",
    title: "Heian Sandan",
    bodyMarkdown: "Tercer kata de la serie Heian.",
    videoUrl: "",
    minBeltRank: "VERDE",
    style: "SHOTOKAN",
    createdAt: "2025-03-15T10:00:00.000Z",
  },
  {
    id: "syl-7",
    slug: "bo-kihon",
    type: "PROGRAM",
    title: "Bo: Kihon básico",
    bodyMarkdown: "Manejo fundamental del bo (bastón largo).",
    videoUrl: "https://example.com/video/bo-kihon",
    minBeltRank: "AZUL",
    style: "KOBUDO",
    createdAt: "2025-04-01T10:00:00.000Z",
  },
  {
    id: "syl-8",
    slug: "kata-tekki-shodan",
    type: "KATA",
    title: "Tekki Shodan",
    bodyMarkdown: "Kata en postura kiba-dachi, base para cinta negra.",
    videoUrl: "",
    minBeltRank: "MARRON",
    style: "SHOTOKAN",
    createdAt: "2025-05-10T10:00:00.000Z",
  },
]
